namespace: app1
metadata:
  claimname: app1-pvc-claim
  name: app1pv
  labels:
    app: app1
spec:
  volumename: app1pv
  selector:
   app: app1

selector:
  matchLabels:
    app: app1

image:
  repository: 779160054397.dkr.ecr.us-east-1.amazonaws.com/lampserver
  tag: 23


volumes:
  persistentVolumeClaim:
          claimName: app1-pvc-claim
  
