apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.namespace }}
  name: app1-ingress
  labels:
   app: {{ .Values.metadata.labels.app }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 300m
    nginx.org/client-max-body-size: "50m"
    cert-manager.io/cluster-issuer: letsencrypt-app1-dev
spec:
  defaultBackend:
     service:
       name: webserver
       port: 
        number: 80
  rules:
    - host: app1.oneclickbazar.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webserver
                port: 
                  number: 80
  tls:
    - secretName: letsencrypt-app1-dev
      hosts:
       - app1.oneclickbazar.com
